version: "3"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/frontend/client/
      - /frontend/client/node_modules
    ports:
      - 3000:3000
