version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/backend
      - /backend/node_modules
    ports:
      - "4000:4000"
    command: npm start
